/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthUserRouteImport } from './routes/auth.user'
import { Route as AuthMemberRouteImport } from './routes/auth.member'
import { Route as UserCategorySlugRouteImport } from './routes/user.category.$slug'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/auth/user',
  path: '/auth/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMemberRoute = AuthMemberRouteImport.update({
  id: '/auth/member',
  path: '/auth/member',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCategorySlugRoute = UserCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/auth/': typeof AuthIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/auth': typeof AuthIndexRoute
  '/user': typeof UserIndexRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/auth/': typeof AuthIndexRoute
  '/user/': typeof UserIndexRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/auth/member'
    | '/auth/user'
    | '/auth/'
    | '/user/'
    | '/user/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/member'
    | '/auth/user'
    | '/auth'
    | '/user'
    | '/user/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/auth/member'
    | '/auth/user'
    | '/auth/'
    | '/user/'
    | '/user/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AuthMemberRoute: typeof AuthMemberRoute
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/user': {
      id: '/auth/user'
      path: '/auth/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/member': {
      id: '/auth/member'
      path: '/auth/member'
      fullPath: '/auth/member'
      preLoaderRoute: typeof AuthMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/category/$slug': {
      id: '/user/category/$slug'
      path: '/category/$slug'
      fullPath: '/user/category/$slug'
      preLoaderRoute: typeof UserCategorySlugRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserCategorySlugRoute: typeof UserCategorySlugRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserCategorySlugRoute: UserCategorySlugRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AuthMemberRoute: AuthMemberRoute,
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
