/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as MemberRouteImport } from './routes/member'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserSettingsRouteImport } from './routes/user.settings'
import { Route as UserSavedRouteImport } from './routes/user.saved'
import { Route as UserReviewsRouteImport } from './routes/user.reviews'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserNotificationsRouteImport } from './routes/user.notifications'
import { Route as UserHistoryRouteImport } from './routes/user.history'
import { Route as UserHelpRouteImport } from './routes/user.help'
import { Route as UserChatRouteImport } from './routes/user.chat'
import { Route as UserBookingsRouteImport } from './routes/user.bookings'
import { Route as MemberSettingsRouteImport } from './routes/member.settings'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberNotificationsRouteImport } from './routes/member.notifications'
import { Route as MemberChatRouteImport } from './routes/member.chat'
import { Route as MemberBookingsRouteImport } from './routes/member.bookings'
import { Route as AuthUserRouteImport } from './routes/auth.user'
import { Route as AuthMemberRouteImport } from './routes/auth.member'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as UserWorkerIdRouteImport } from './routes/user.worker.$id'
import { Route as UserChatOtherIdRouteImport } from './routes/user.chat.$otherId'
import { Route as UserCategorySlugRouteImport } from './routes/user.category.$slug'
import { Route as MemberChatOtherIdRouteImport } from './routes/member.chat.$otherId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserSavedRoute = UserSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => UserRoute,
} as any)
const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserRoute,
} as any)
const UserHistoryRoute = UserHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => UserRoute,
} as any)
const UserHelpRoute = UserHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => UserRoute,
} as any)
const UserChatRoute = UserChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => UserRoute,
} as any)
const UserBookingsRoute = UserBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => UserRoute,
} as any)
const MemberSettingsRoute = MemberSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNotificationsRoute = MemberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MemberRoute,
} as any)
const MemberChatRoute = MemberChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookingsRoute = MemberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MemberRoute,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/auth/user',
  path: '/auth/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMemberRoute = AuthMemberRouteImport.update({
  id: '/auth/member',
  path: '/auth/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserWorkerIdRoute = UserWorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => UserRoute,
} as any)
const UserChatOtherIdRoute = UserChatOtherIdRouteImport.update({
  id: '/$otherId',
  path: '/$otherId',
  getParentRoute: () => UserChatRoute,
} as any)
const UserCategorySlugRoute = UserCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => UserRoute,
} as any)
const MemberChatOtherIdRoute = MemberChatOtherIdRouteImport.update({
  id: '/$otherId',
  path: '/$otherId',
  getParentRoute: () => MemberChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/chat': typeof MemberChatRouteWithChildren
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/settings': typeof MemberSettingsRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/chat': typeof UserChatRouteWithChildren
  '/user/help': typeof UserHelpRoute
  '/user/history': typeof UserHistoryRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/saved': typeof UserSavedRoute
  '/user/settings': typeof UserSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/member/': typeof MemberIndexRoute
  '/user/': typeof UserIndexRoute
  '/member/chat/$otherId': typeof MemberChatOtherIdRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
  '/user/chat/$otherId': typeof UserChatOtherIdRoute
  '/user/worker/$id': typeof UserWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/chat': typeof MemberChatRouteWithChildren
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/settings': typeof MemberSettingsRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/chat': typeof UserChatRouteWithChildren
  '/user/help': typeof UserHelpRoute
  '/user/history': typeof UserHistoryRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/saved': typeof UserSavedRoute
  '/user/settings': typeof UserSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/member': typeof MemberIndexRoute
  '/user': typeof UserIndexRoute
  '/member/chat/$otherId': typeof MemberChatOtherIdRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
  '/user/chat/$otherId': typeof UserChatOtherIdRoute
  '/user/worker/$id': typeof UserWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/member': typeof AuthMemberRoute
  '/auth/user': typeof AuthUserRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/chat': typeof MemberChatRouteWithChildren
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/settings': typeof MemberSettingsRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/chat': typeof UserChatRouteWithChildren
  '/user/help': typeof UserHelpRoute
  '/user/history': typeof UserHistoryRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/saved': typeof UserSavedRoute
  '/user/settings': typeof UserSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/member/': typeof MemberIndexRoute
  '/user/': typeof UserIndexRoute
  '/member/chat/$otherId': typeof MemberChatOtherIdRoute
  '/user/category/$slug': typeof UserCategorySlugRoute
  '/user/chat/$otherId': typeof UserChatOtherIdRoute
  '/user/worker/$id': typeof UserWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/user'
    | '/auth/login'
    | '/auth/member'
    | '/auth/user'
    | '/member/bookings'
    | '/member/chat'
    | '/member/notifications'
    | '/member/profile'
    | '/member/settings'
    | '/user/bookings'
    | '/user/chat'
    | '/user/help'
    | '/user/history'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/user/saved'
    | '/user/settings'
    | '/admin/'
    | '/auth/'
    | '/member/'
    | '/user/'
    | '/member/chat/$otherId'
    | '/user/category/$slug'
    | '/user/chat/$otherId'
    | '/user/worker/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/member'
    | '/auth/user'
    | '/member/bookings'
    | '/member/chat'
    | '/member/notifications'
    | '/member/profile'
    | '/member/settings'
    | '/user/bookings'
    | '/user/chat'
    | '/user/help'
    | '/user/history'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/user/saved'
    | '/user/settings'
    | '/admin'
    | '/auth'
    | '/member'
    | '/user'
    | '/member/chat/$otherId'
    | '/user/category/$slug'
    | '/user/chat/$otherId'
    | '/user/worker/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/user'
    | '/auth/login'
    | '/auth/member'
    | '/auth/user'
    | '/member/bookings'
    | '/member/chat'
    | '/member/notifications'
    | '/member/profile'
    | '/member/settings'
    | '/user/bookings'
    | '/user/chat'
    | '/user/help'
    | '/user/history'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/user/saved'
    | '/user/settings'
    | '/admin/'
    | '/auth/'
    | '/member/'
    | '/user/'
    | '/member/chat/$otherId'
    | '/user/category/$slug'
    | '/user/chat/$otherId'
    | '/user/worker/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MemberRoute: typeof MemberRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMemberRoute: typeof AuthMemberRoute
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/saved': {
      id: '/user/saved'
      path: '/saved'
      fullPath: '/user/saved'
      preLoaderRoute: typeof UserSavedRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/reviews': {
      id: '/user/reviews'
      path: '/reviews'
      fullPath: '/user/reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/notifications': {
      id: '/user/notifications'
      path: '/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/history': {
      id: '/user/history'
      path: '/history'
      fullPath: '/user/history'
      preLoaderRoute: typeof UserHistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/help': {
      id: '/user/help'
      path: '/help'
      fullPath: '/user/help'
      preLoaderRoute: typeof UserHelpRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/chat': {
      id: '/user/chat'
      path: '/chat'
      fullPath: '/user/chat'
      preLoaderRoute: typeof UserChatRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/bookings': {
      id: '/user/bookings'
      path: '/bookings'
      fullPath: '/user/bookings'
      preLoaderRoute: typeof UserBookingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/member/settings': {
      id: '/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof MemberSettingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/notifications': {
      id: '/member/notifications'
      path: '/notifications'
      fullPath: '/member/notifications'
      preLoaderRoute: typeof MemberNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/chat': {
      id: '/member/chat'
      path: '/chat'
      fullPath: '/member/chat'
      preLoaderRoute: typeof MemberChatRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/bookings': {
      id: '/member/bookings'
      path: '/bookings'
      fullPath: '/member/bookings'
      preLoaderRoute: typeof MemberBookingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/auth/user': {
      id: '/auth/user'
      path: '/auth/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/member': {
      id: '/auth/member'
      path: '/auth/member'
      fullPath: '/auth/member'
      preLoaderRoute: typeof AuthMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/worker/$id': {
      id: '/user/worker/$id'
      path: '/worker/$id'
      fullPath: '/user/worker/$id'
      preLoaderRoute: typeof UserWorkerIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/chat/$otherId': {
      id: '/user/chat/$otherId'
      path: '/$otherId'
      fullPath: '/user/chat/$otherId'
      preLoaderRoute: typeof UserChatOtherIdRouteImport
      parentRoute: typeof UserChatRoute
    }
    '/user/category/$slug': {
      id: '/user/category/$slug'
      path: '/category/$slug'
      fullPath: '/user/category/$slug'
      preLoaderRoute: typeof UserCategorySlugRouteImport
      parentRoute: typeof UserRoute
    }
    '/member/chat/$otherId': {
      id: '/member/chat/$otherId'
      path: '/$otherId'
      fullPath: '/member/chat/$otherId'
      preLoaderRoute: typeof MemberChatOtherIdRouteImport
      parentRoute: typeof MemberChatRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberChatRouteChildren {
  MemberChatOtherIdRoute: typeof MemberChatOtherIdRoute
}

const MemberChatRouteChildren: MemberChatRouteChildren = {
  MemberChatOtherIdRoute: MemberChatOtherIdRoute,
}

const MemberChatRouteWithChildren = MemberChatRoute._addFileChildren(
  MemberChatRouteChildren,
)

interface MemberRouteChildren {
  MemberBookingsRoute: typeof MemberBookingsRoute
  MemberChatRoute: typeof MemberChatRouteWithChildren
  MemberNotificationsRoute: typeof MemberNotificationsRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberSettingsRoute: typeof MemberSettingsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberBookingsRoute: MemberBookingsRoute,
  MemberChatRoute: MemberChatRouteWithChildren,
  MemberNotificationsRoute: MemberNotificationsRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberSettingsRoute: MemberSettingsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface UserChatRouteChildren {
  UserChatOtherIdRoute: typeof UserChatOtherIdRoute
}

const UserChatRouteChildren: UserChatRouteChildren = {
  UserChatOtherIdRoute: UserChatOtherIdRoute,
}

const UserChatRouteWithChildren = UserChatRoute._addFileChildren(
  UserChatRouteChildren,
)

interface UserRouteChildren {
  UserBookingsRoute: typeof UserBookingsRoute
  UserChatRoute: typeof UserChatRouteWithChildren
  UserHelpRoute: typeof UserHelpRoute
  UserHistoryRoute: typeof UserHistoryRoute
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReviewsRoute: typeof UserReviewsRoute
  UserSavedRoute: typeof UserSavedRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserIndexRoute: typeof UserIndexRoute
  UserCategorySlugRoute: typeof UserCategorySlugRoute
  UserWorkerIdRoute: typeof UserWorkerIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBookingsRoute: UserBookingsRoute,
  UserChatRoute: UserChatRouteWithChildren,
  UserHelpRoute: UserHelpRoute,
  UserHistoryRoute: UserHistoryRoute,
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRoute,
  UserReviewsRoute: UserReviewsRoute,
  UserSavedRoute: UserSavedRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserIndexRoute: UserIndexRoute,
  UserCategorySlugRoute: UserCategorySlugRoute,
  UserWorkerIdRoute: UserWorkerIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MemberRoute: MemberRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthMemberRoute: AuthMemberRoute,
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
